//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiddingTestX {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resoureces {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resoureces() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BiddingTestX.Resoureces", typeof(Resoureces).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;PublicIdentifier&quot;: &quot;80947815-0d74-4f5b-9128-859f591344e6&quot;,
        ///    &quot;Description&quot;: &quot;I test Dev&quot;,
        ///    &quot;Type&quot;: &quot;DK-1&quot;
        /// }.
        /// </summary>
        public static string Aktion {
            get {
                return ResourceManager.GetString("Aktion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;PublicIdentifier&quot;: &quot;80947815-0d74-4f5b-9128-859f591344e6&quot;,
        ///    &quot;Description&quot;: &quot;I test Dev&quot;,
        ///    &quot;Type&quot;: &quot;DK-1&quot;
        ///  },
        ///  {
        ///    &quot;PublicIdentifier&quot;: &quot;aabfd65d-9a9a-43e6-9e69-c7ce09c86d16&quot;,
        ///    &quot;Description&quot;: &quot;I test Dev&quot;,
        ///    &quot;Type&quot;: &quot;DK-2&quot;
        ///  }
        ///].
        /// </summary>
        public static string Aktions {
            get {
                return ResourceManager.GetString("Aktions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;PublicIdentifier&quot;: &quot;b88c198f-432a-4b0c-a5a9-f3e903692a5c&quot;,
        ///    &quot;Name&quot;: &quot;Energinet&quot;,
        ///    &quot;City&quot;: &quot;Fredericia&quot;,
        ///    &quot;ZipCode&quot;: 7000,
        ///    &quot;Road&quot;: &quot;Tonne Kjærsvej&quot;,
        ///    &quot;StreetNumber&quot;: &quot;65&quot;,
        ///    &quot;XmlIdentifier&quot;: 5790000432752
        ///  }.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;PublicIdentifier&quot;: &quot;b88c198f-432a-4b0c-a5a9-f3e903692a5c&quot;,
        ///    &quot;Name&quot;: &quot;Energinet&quot;,
        ///    &quot;City&quot;: &quot;Fredericia&quot;,
        ///    &quot;ZipCode&quot;: 7000,
        ///    &quot;Road&quot;: &quot;Tonne Kjærsvej&quot;,
        ///    &quot;StreetNumber&quot;: &quot;65&quot;,
        ///    &quot;XmlIdentifier&quot;: 5790000432752
        ///  },
        ///  {
        ///    &quot;PublicIdentifier&quot;: &quot;71708e60-c4dd-49f0-87f2-bd1b2ba5574b&quot;,
        ///    &quot;Name&quot;: &quot;Ørsted&quot;,
        ///    &quot;City&quot;: &quot;Skærbæk&quot;,
        ///    &quot;ZipCode&quot;: 7000,
        ///    &quot;Road&quot;: &quot;Kraftværksvej&quot;,
        ///    &quot;StreetNumber&quot;: &quot;53&quot;,
        ///    &quot;XmlIdentifier&quot;: 1
        ///  },
        ///  {
        ///    &quot;PublicIdentifier&quot;: &quot;470d1237 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Companys {
            get {
                return ResourceManager.GetString("Companys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;BidDocument xmlns=&quot;http://www.energinet.dk/schemas/BalRespXML/BidDocument/v13&quot; xmlns:ecc=&quot;etso-core-cmpts.xsd&quot; xmlns:ecl=&quot;etso-code-lists.xsd&quot; xmlns:ns2=&quot;http://www.energinet.dk/schemas/BalRespXML/BidDocument/v13&quot; xmlns:ns4=&quot;http://www.energinet.dk/schemas/BalRespXML/MessageHeader/v13&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xsi:schemaLocation=&quot;http://www.energinet.dk/schemas/BalRespXML/BidDocument/v13  ../BidDocument-13.xsd&quot;&gt;
        ///	&lt;ns4:MessageHeader&gt;
        ///		&lt;ns4:DocumentPublicPublicIdentifierentifi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string mFRR_regulerkraftbud {
            get {
                return ResourceManager.GetString("mFRR_regulerkraftbud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;publicIdentifier&quot;: &quot;f7d5fb21-e0b7-4d78-a77f-4bacec6d4549&quot;,
        ///  &quot;company&quot;: {
        ///    &quot;publicIdentifier&quot;: &quot;b88c198f-432a-4b0c-a5a9-f3e903692a5c&quot;,
        ///    &quot;name&quot;: &quot;Energinet&quot;,
        ///    &quot;city&quot;: &quot;Fredericia&quot;,
        ///    &quot;zipCode&quot;: 7000,
        ///    &quot;road&quot;: &quot;Tonne Kjærsvej&quot;,
        ///    &quot;streetNumber&quot;: &quot;65&quot;,
        ///    &quot;xmlIdentifier&quot;: 5790000432752
        ///  },
        ///  &quot;user&quot;: {
        ///    &quot;id&quot;: &quot;9c969fc9-149a-4de6-a055-deced6b52bd6&quot;,
        ///    &quot;userName&quot;: &quot;Test&quot;,
        ///    &quot;company&quot;: {
        ///      &quot;publicIdentifier&quot;: &quot;71708e60-c4dd-49f0-87f2-bd1b2ba5574b&quot;,
        ///      &quot;name&quot;: &quot;Ø [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RawBid {
            get {
                return ResourceManager.GetString("RawBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///{
        ///  &quot;publicIdentifier&quot;: &quot;f7d5fb21-e0b7-4d78-a77f-4bacec6d4549&quot;,
        ///  &quot;company&quot;: {
        ///    &quot;publicIdentifier&quot;: &quot;b88c198f-432a-4b0c-a5a9-f3e903692a5c&quot;,
        ///    &quot;name&quot;: &quot;Energinet&quot;,
        ///    &quot;city&quot;: &quot;Fredericia&quot;,
        ///    &quot;zipCode&quot;: 7000,
        ///    &quot;road&quot;: &quot;Tonne Kjærsvej&quot;,
        ///    &quot;streetNumber&quot;: &quot;65&quot;,
        ///    &quot;xmlIdentifier&quot;: 5790000432752
        ///  },
        ///  &quot;user&quot;: {
        ///    &quot;id&quot;: &quot;9c969fc9-149a-4de6-a055-deced6b52bd6&quot;,
        ///    &quot;userName&quot;: &quot;Test&quot;,
        ///    &quot;company&quot;: {
        ///      &quot;publicIdentifier&quot;: &quot;71708e60-c4dd-49f0-87f2-bd1b2ba5574b&quot;,
        ///      &quot;name&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RawBids {
            get {
                return ResourceManager.GetString("RawBids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;id&quot;: &quot;9c969fc9-149a-4de6-a055-deced6b52bd6&quot;,
        ///  &quot;userName&quot;: &quot;Test&quot;,
        ///  &quot;company&quot;: {
        ///    &quot;publicIdentifier&quot;: &quot;71708e60-c4dd-49f0-87f2-bd1b2ba5574b&quot;,
        ///    &quot;name&quot;: &quot;Ørsted&quot;,
        ///    &quot;city&quot;: &quot;Skærbæk&quot;,
        ///    &quot;zipCode&quot;: 7000,
        ///    &quot;road&quot;: &quot;Kraftværksvej&quot;,
        ///    &quot;streetNumber&quot;: &quot;53&quot;,
        ///    &quot;xmlIdentifier&quot;: 1
        ///  },
        ///  &quot;roles&quot;: 1
        ///}.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;id&quot;: &quot;29e0e8e4-1634-4ab2-ac53-a3e269bec6f6&quot;,
        ///    &quot;userName&quot;: &quot;Test2&quot;,
        ///    &quot;company&quot;: {
        ///      &quot;publicIdentifier&quot;: &quot;00000000-0000-0000-0000-000000000000&quot;
        ///    },
        ///    &quot;roles&quot;: 1
        ///  },
        ///  {
        ///    &quot;id&quot;: &quot;aadc1c0e-068c-47f8-a996-a56bf37e04eb&quot;,
        ///    &quot;userName&quot;: &quot;Ørsted&quot;,
        ///    &quot;company&quot;: {
        ///      &quot;publicIdentifier&quot;: &quot;00000000-0000-0000-0000-000000000000&quot;
        ///    },
        ///    &quot;roles&quot;: 0
        ///  },
        ///  {
        ///    &quot;id&quot;: &quot;9c969fc9-149a-4de6-a055-deced6b52bd6&quot;,
        ///    &quot;userName&quot;: &quot;Test&quot;,
        ///    &quot;company&quot;: {
        ///      &quot;publicIden [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
    }
}
