//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntergrationsTestX {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Seetings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Seetings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IntergrationsTestX.Seetings", typeof(Seetings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///  &quot;PublicIdentifier&quot;: &quot;80947815-0d74-4f5b-9128-859f591344e6&quot;,
        ///  &quot;Description&quot;: &quot;Dette er en test&quot;,
        ///  &quot;Type&quot;: &quot;Test&quot;
        ///  },{
        ///  &quot;PublicIdentifier&quot;: &quot;e19ed157-8866-46eb-9cc3-a749510f9198&quot;,
        ///  &quot;Description&quot;: &quot;Dette er stadig en test&quot;,
        ///  &quot;Type&quot;: &quot;Test&quot;
        ///  },{
        ///  &quot;PublicIdentifier&quot;: &quot;5967df2d-bf92-495e-b898-b5ea43748d6a&quot;,
        ///  &quot;Description&quot;: &quot;Dette er alser stadig en test&quot;,
        ///  &quot;Type&quot;: &quot;Test&quot;
        ///  }
        ///].
        /// </summary>
        public static string Aktions {
            get {
                return ResourceManager.GetString("Aktions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///  &quot;PublicIdentifier&quot;: &quot;0b4c004c-550a-45a0-9c58-dbc7ebfdf78a&quot;,
        ///  &quot;City&quot;: &quot;Fredericia&quot;,
        ///  &quot;ZipCode&quot;: &quot;7000&quot;,
        ///  &quot;Name&quot;: &quot;Test&quot;,
        ///  &quot;Road&quot;: &quot;TestSt.&quot;,
        ///  &quot;StreetNumber&quot;: &quot;224A&quot;
        ///  },
        ///  {
        ///  &quot;PublicIdentifier&quot;: &quot;14eb7383-7518-4ddb-a715-ea6ddd28213f&quot;,
        ///  &quot;City&quot;: &quot;Fredericia&quot;,
        ///  &quot;ZipCode&quot;: &quot;7000&quot;,
        ///  &quot;Name&quot;: &quot;Energinet&quot;,
        ///  &quot;Road&quot;: &quot;Tonne Kjærsvej&quot;,
        ///  &quot;StreetNumber&quot;: &quot;65&quot;
        ///  }
        ///].
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;BidDocument xmlns=&quot;http://www.energinet.dk/schemas/BalRespXML/BidDocument/v13&quot; xmlns:ecc=&quot;etso-core-cmpts.xsd&quot; xmlns:ecl=&quot;etso-code-lists.xsd&quot; xmlns:ns2=&quot;http://www.energinet.dk/schemas/BalRespXML/BidDocument/v13&quot; xmlns:ns4=&quot;http://www.energinet.dk/schemas/BalRespXML/MessageHeader/v13&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xsi:schemaLocation=&quot;http://www.energinet.dk/schemas/BalRespXML/BidDocument/v13  ../BidDocument-13.xsd&quot;&gt;
        ///	&lt;ns4:MessageHeader&gt;
        ///		&lt;ns4:DocumentPublicPublicIdentifierentifi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string mFRR_regulerkraftbud {
            get {
                return ResourceManager.GetString("mFRR_regulerkraftbud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [    
        ///  {
        ///    &quot;Id&quot;: &quot;1&quot;,
        ///    &quot;PublicIdentifier&quot;: &quot;891f42cf-725a-4469-85ba-83e4e49f01d3&quot;,
        ///    &quot;Company&quot;:{&quot;PublicIdentifier&quot;:&quot;0b4c004c-550a-45a0-9c58-dbc7ebfdf78a&quot;},
        ///    &quot;Areas&quot;:{&quot;PublicIdentifier&quot;:&quot;80947815-0d74-4f5b-9128-859f591344e6&quot;}        
        ///  }
        ///].
        /// </summary>
        public static string RawBid {
            get {
                return ResourceManager.GetString("RawBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;Id&quot;:&quot;616d66b9-364d-4e08-8f52-630d602136bc&quot;,
        ///    &quot;UserName&quot;:&quot;Test&quot;,
        ///    &quot;Company&quot;:
        ///    {
        ///      &quot;PublicIdentifier&quot;:&quot;14eb7383-7518-4ddb-a715-ea6ddd28213f&quot;
        ///    },
        ///    &quot;Roles&quot;:1}].
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
    }
}
